name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
Set your workflow to run on pull_request events that target the master branch

on:
  pull_request:
    branches:
    - master
Set your workflow to run every day of the week from Monday to Friday at 2:00 UTC

on:
  schedule:
  - cron: "0 2 * * 1-5"
For more information, see "Events that trigger workflows."
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
llowing snippet into your .yml file.

Version: v1.0.3 
- name: Cache
  uses: actions/cache@v1.0.3
  with:
    # A directory to store and save the cache
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    restore-keys: # optional
